site_name: Robert W Szarek
site_url: "https://szarr.github.io"
site_description: "Official Website of Robert Szarek"
repo_url: https://github.com/SzarR/website
repo_name: szarr/website
edit_uri: edit/master/docs/
copyright: "&copy; 2025. v1.0. Last Updated on March 8, 2025"

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png

  font:
    text: Roboto
    code: Noto Sans Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.inline
    - toc.permalink
    - navigation.top

  palette:
    # Automatically switches between light & dark modes based on system
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode

plugins:
  - search
  - privacy
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      post_url_format: "posts/{file}"
      pagination_per_page: 3
 # - gallery:
 #     examples_dirs: docs/images
 #     gallery_dirs: docs/generated/images

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  cli: "SzarR"
  bio: "<br> <br> Hi, I'm Robert! I hold a Master’s degree in Industrial-Organizational Psychology, and my professional journey began in test development and psychometrics. Over time, my passion for data and analytics naturally guided me toward the fields of machine learning and data science. Today, I specialize in people analytics, where I combine statistical modeling with insights into human behavior. In my day-to-day work, I use R, Linux and Python to create custom machine learning models. These models allow me to tackle a variety of challenges, from analyzing open-ended text responses to predicting employee turnover. Additionally, I enjoy building customized Shiny dashboard apps that help solve a specific use case, like network analysis. Data science offers me the perfect intersection of my technical programming skills and my ability to solve complex, business-critical problems. When I'm not diving into data, you can find me in the sky, flying airplanes, or out in nature, enjoying the tranquility and beauty of the great outdoors.
 <br> <br>"
  generator: false
  subtitle: "Senior Data Scientist"
  avatar: assets/avatar.png
  socials:
    - linkedin: https://www.linkedin.com/in/robert-szarek-3163a632/
    - github: https://www.github.com/szarr
    - email: mailto:szarekr@gmail.com
    - file: https://szarr.github.io/resume/resume.html
    - file-pdf: https://szarr.github.io/resume/resume.pdf

extra_css:
  - stylesheets/extra.css