site_name: Robert W Szarek
site_url: "https://szarr.github.io"
site_description: "Official Website of Robert Szarek"
repo_url: https://github.com/SzarR/website
repo_name: szarr/website
edit_uri: edit/master/docs/
copyright: "&copy; 2025. Last Updated on March 8, 2025"

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png

  font:
    text: Roboto
    code: Noto Sans Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.inline
    - toc.permalink
    - navigation.top

  palette:
    # Automatically switches between light & dark modes based on system
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode

plugins:
  - search
  - privacy
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      post_url_format: "posts/{file}"
      pagination_per_page: 3

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  cli: "SzarR"
  bio: "<br> <br> Robert Szarek is an I/O Psychologist turned Data Scientist. His primary field is within people analytics, where he leverages machine learning and natural language processing to craft compelling stories around organizational behavior. Data science has provided me with the technological tools required, while my academic degree provides a comprehensive understanding of human behavior in the workplace. The intersection of these two fields provides the opportunity to make a significant impact in the workplace. Aside from work, I’m an aviation geek with a FAA pilot’s license with more than 200 hours logged in the past decade. <br> <br>"
  generator: false
  subtitle: "Senior Data Scientist"
  avatar: assets/avatar.png
  socials:
    - linkedin: https://www.linkedin.com/in/nathancatania/
    - github: https://www.github.com/szarr
    - email: szarekr@gmail.com

extra_css:
  - stylesheets/extra.css