site_name: Nathan Catania
site_url: "https://nathancatania.com"
site_description: "Official Website of Nathan Catania"
repo_url: https://github.com/nathancatania/website
repo_name: nathancatania/website
edit_uri: edit/master/docs/
copyright: "&copy; 2024, Nathan Catania"

theme:
  name: material
  custom_dir: overrides
  #logo: assets/avatar.png
  icon:
    repo: material/github
    #logo: octicons/cpu-16
    logo: material/hand-wave



  font:
    text: Inter
    code: Noto Sans Mono
  
  palette:
    # Automatically switches between light & dark modes based on system
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode


plugins:
  - search
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      post_url_format: "posts/{slug}"



      # categories_url_format: "posts/{slug}"
      


extra:
  cli: "$ cd /home/nathan"
  generator: false
  subtitle: "Engineer // Australia // AI // Cybersec"
  avatar: assets/avatar.png
  socials:
    - linkedin: https://www.linkedin.com/in/nathancatania/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
